
sudo: required
services:
  - docker

before_install:
  - docker build -t svenrivera/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svenrivera/react-test npm test 

after_success:
  - docker build -t svenrivera/multi-client ./client
  - docker build -t svenrivera/multi-server ./server
  - docker build -t svenrivera/multi-nginx ./nginx
  - docker build -t svenrivera/multi-worker ./worker

# Log into Docker CLI
# Add the environment variables in the travis-ci site
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push the images to Docker Hub
  - docker push svenrivera/multi-client
  - docker push svenrivera/multi-server
  - docker push svenrivera/multi-nginx
  - docker push svenrivera/multi-worker
